spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/my_spring?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000

---
spring:
  config:
    activate:
      on-profile: redis-dev

---
spring:
  config:
    activate:
      on-profile: redis-test

---
spring:
  config:
    activate:
      on-profile: redis-prod