server:
  port: 8500
  servlet:
    context-path: /user

spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: prod